=== MightyMonkey/Cours/XML/annuaire2.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema elementFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="numerosType">
		<xs:sequence>
			<xs:element name="contact" type="contactType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="contactType">
		<xs:sequence>
			<xs:element name="nom" type="xs:string"/>
			<xs:element name="prenom" type="xs:string"/>
			<xs:element name="telephone" type="xs:string" minOccurs="0"/>
			<xs:element name="email" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="titre" type="xs:string" use="required"/>
		<xs:attribute name="techno" type="xs:string" use="optional"/>
	</xs:complexType>

	<xs:simpleType name="technoType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="XML"/>
			<xs:enumeration value="Java"/>
			<xs:enumeration value="Autre"/>
		</xs:sequence>
	</xs:simpleType>

	<xs:simpleType name="intListe">
		 <xs:list itemType="xs:integer"/>
	</xs:simpleType>

	<xs:simpleType name="telType">
		<xs:restriction base="intListe">
           		<xs:length value="5"/>
        	</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="emailType">
		<xs:restriction base="xs:string">
			  <xs:pattern value="[a-z]+@[a-z]+\.[a-z]{2,3}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="numeros" type="numerosType"/>
</xs:schema>

=== MightyMonkey/Cours/XML/annuaire2.xml
<?xml version="1.0" encoding="UTF-8"?>
<numeros xsi:noNamespaceSchemaLocation="annuaire2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <contact titre="contact1" techno="XML">
        <nom>Charrier</nom>
        <prenom>Etienne</prenom>
        <telephone>06 06 06 06 06</telephone>
        <email>etienne@insacvl.fr</email>
    </contact>

    <contact titre="contact2">
        <nom>Doe</nom>
        <prenom>John</prenom>
        <email>john@insacvl.fr</email>
        <email>john@ensibourges.fr</email>
    </contact>

    <contact titre="contact3" techno="Java">
        <nom>Geveaux</nom>
        <prenom>Damien</prenom>
        <email>damien@insacvl.fr</email>
    </contact>

    <contact titre="contact4">
        <nom>Klopfenstein</nom>
        <prenom>Luc</prenom>
        <telephone>07 07 07 07 07</telephone>
        <email>luc@insacvl.fr</email>
    </contact>

</numeros>
